apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testwebapp-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: testwebapp-pod
    spec:
      containers:
      - name: testwebapp
        image: replace-your-image-URL
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080