apiVersion: v1
kind: Service
metadata:
  name: testwebapp-service
spec:
  selector:
    app: testwebapp-pod
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer